
function loadContent() {
    const links = document.querySelectorAll('a');
    const prevButton = document.querySelector('#goToPrev');
    const nextButton = document.querySelector('#goToNext');
    const companies = document.querySelector('.companies');
    let current = 0;
    const MAX_DAYS = 30;
    const MAX_STARS = 5;

    // Global data object
    const data = [
        {
            name: "google",
            link: "http://www.google.com",
            description: "Google LLC is an American multinational corporation and technology company focusing on online advertising, search engine technology, cloud computing, computer software, quantum computing, e-commerce, consumer electronics, and artificial intelligence (AI). It has been referred to as the most powerful company in the world and is one of the world's most valuable brands due to its market dominance, data collection, and technological advantages in the field of AI. Google's parent company, Alphabet Inc., is one of the five Big Tech companies, alongside Amazon, Apple, Meta, and Microsoft.",
            title: "https://en.wikipedia.org/wiki/Google",
            logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
            rating: 4.0,
            reviews: 2278,
            employees: 72053,
            openings: 1278,
            pto: {
                full: {
                    general: 15,
                    total: 20,
                    volunteering: 25,
                },
                part: {
                    general: 7,
                    sick: 0
                }
            }
        },
        {
            name: "amazon",
            link: "https://www.amazon.com/",
            description: "Amazon.com, Inc., doing business as Amazon, is an American multinational technology company, engaged in e-commerce, cloud computing, online advertising, digital streaming, and artificial intelligence. It is considered one of the Big Five American technology companies; the other four are Alphabet (parent company of Google), Apple, Meta (parent company of Facebook), and Microsoft.",
            title: "https://en.wikipedia.org/wiki/Amazon_(company)",
            logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
            rating: 4.5,
            reviews: 6019,
            employees: 1525000,
            openings: 27450,
            pto: {
                full: {
                    general: 20,
                    total: 25,
                    volunteering: 15,
                },
                part: {
                    general: 10,
                    sick: 2
                }
            }
        },
        {
            name: "ibm",
            link: "https://www.ibm.com",
            description: "International Business Machines Corporation (using the trademark IBM), nicknamed Big Blue, is an American multinational technology company headquartered in Armonk, New York and present in over 175 countries. IBM is the largest industrial research organization in the world, with 19 research facilities across a dozen countries, having held the record for most annual U.S. patents generated by a business for 29 consecutive years from 1993 to 2021.",
            title: "https://en.wikipedia.org/wiki/IBM",
            logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg",
            rating: 3.0,
            reviews: 9056,
            employees: 282200,
            openings: 5080,
            pto: {
                full: {
                    general: 25,
                    total: 25,
                    volunteering: 10,
                },
                part: {
                    general: 5,
                    sick: 5
                }
            }
        },
        {
            name: "cisco",
            link: "https://www.cisco.com/",
            description: "Cisco Systems, Inc. (using the trademark Cisco) is an American multinational digital communications technology conglomerate corporation headquartered in San Jose, California. Cisco develops, manufactures, and sells networking hardware, software, telecommunications equipment and other high-technology services and products. Cisco specializes in specific tech markets, such as the Internet of things (IoT), domain security, videoconferencing, and energy management with products including Webex, OpenDNS, Jabber, Duo Security, Silicon One, and Jasper.",
            title: "https://en.wikipedia.org/wiki/Cisco",
            logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Cisco_logo_blue_2016.svg",
            rating: 3.5,
            reviews: 8118,
            employees: 84900,
            openings: 1528,
            pto: {
                full: {
                    general: 15,
                    total: 15,
                    volunteering: 0,
                },
                part: {
                    general: 5,
                    sick: 1
                }
            }
        }
    ];

    // Marcin Malecki's thumbnail hack
    if (navigator.userAgent.includes("Headless")) {
        document.body.style.setProperty("padding-block-end", "0");
        document.body.style.setProperty("margin-block-start", "152px");
        document.body.style.setProperty("min-block-size", "0");
        document.body.style.setProperty("block-size", "calc(100vh - 304px)");
        document.body.style.setProperty("position", "relative");
    }

    function generateCompanyPages() {

        companies.innerHTML = data.map((item, index) => {

            // generate (right) information section
            const infoSection = document.createElement('section');
            infoSection.classList.add('info-section');
            infoSection.innerHTML = `<div class="name-bl">
                    <span class="company-num">#${index + 1}.</span>
                    <span class="company-name">${item.name}</span>
                </div>
                <a href="${item.link}" class="company-link">${item.link}</a>    
                <p class="company-description" title="${item.title}"}>
                    ${item.description}
                </p>`;

            // generate (left) logo section
            const logoSection = document.createElement('section');
            logoSection.classList.add('logo-section');

            // generate logo
            const logo = document.createElement('div');
            logo.classList.add('logo');
            logo.innerHTML = `<img src="${item.logo}" alt="image of company logo">`;

            // generate reviews text content
            const reviews = document.createElement('div');
            reviews.classList.add('reviews-bl');
            reviews.innerHTML = `<span class="reviews">${item.reviews}</span>
                <span>Reviews</span>`;
            
            // generate the star ratings
            const ratings = document.createElement('div');
            ratings.classList.add('ratings');

            const isHalfStar = !(item.rating % 1 === 0);
            let rating = '';
            for (let i = 1; i <= MAX_STARS; i++) {
                if (isHalfStar && i === Math.ceil(item.rating) ) {
                    rating = rating + '<i class="rating active fa-solid fa-star-half-stroke"></i>';
                } else if (i <= Math.floor(item.rating)) {
                    rating = rating + '<i class="rating active fa-solid fa-star"></i>';
                } else {
                    rating = rating + '<i class="rating fa-solid fa-star"></i>';
                }
            }
            ratings.innerHTML = rating;

            // join/concatentate all the child elements 
            logoSection.innerHTML = logo.outerHTML + ratings.outerHTML + reviews.outerHTML;

            // generate parent company container 
            const company = document.createElement('div');
            company.classList.add('company');
            company.setAttribute('data-value', `${index}`);

            // append the child sections
            company.appendChild(logoSection);
            company.appendChild(infoSection);

            return company.outerHTML;
        }).join('');

    }

    function displayPTO(number) {
        const totalEmployees = document.querySelector('.total-employees');
        const jobOpenings = document.querySelector('.job-openings');
        const bars = document.querySelectorAll('.progress');
        const values = document.querySelectorAll('.progress-value');

        totalEmployees.textContent = data[number].employees.toLocaleString();
        jobOpenings.textContent = data[number].openings.toLocaleString();

        // General PTO
        bars[0].style.width = `${data[number].pto.full.general/MAX_DAYS * 100}%`;
        values[0].textContent = data[number].pto.full.general;

        // Total PTO after 5 years
        bars[1].style.width = `${data[number].pto.full.total/MAX_DAYS * 100}%`;
        values[1].textContent = data[number].pto.full.total;

        // For volunteering
        bars[2].style.width = `${data[number].pto.full.volunteering/MAX_DAYS * 100}%`;
        values[2].textContent = data[number].pto.full.volunteering;

        // General PTO for part-timers
        bars[3].style.width = `${data[number].pto.part.general/MAX_DAYS * 100}%`;
        values[3].textContent = data[number].pto.part.general;

        // # Sick days for part-timers
        bars[4].style.width = `${data[number].pto.part.sick/MAX_DAYS * 100}%`;
        values[4].textContent = data[number].pto.part.sick;
    }

    function moveToPage(number) {
        const page = document.querySelector(`.company[data-value="${number}"]`);

        companies.style.left = `${-1 * page.offsetLeft}px`;
        displayPTO(current);
    }
    
    function move(direction) {
        direction === 'forward' ? current++ : current--;
        current = current < 0 ? data.length - 1 : current;
        current = current > (data.length - 1) ? 0 : current;
        
        moveToPage(current);
    }

    // On page load... 
    generateCompanyPages();
    moveToPage(current);

    // Event Listeners
    links.forEach(link => link.addEventListener ('click', (e) => e.preventDefault()));
    prevButton.addEventListener('click', (e) => move('back'));
    nextButton.addEventListener('click', (e) => move('forward'));
    window.addEventListener('resize', () => moveToPage(current));
}

window.addEventListener('DOMContentLoaded', loadContent);